### ISSUE TITLE
Support Typescript 1.4

### ISSUE THREAD

**Issue by egaga** [EvidentSolutions/apina#21]
The generated api file uses a `const´ exactly once. For this only, the Apina disgards support for 1.4 or lower versions of Typescript when using ES5 target generation.

The 1.4 version of Typescript should be fully supported.

**Comment by komu** [comment]
I understand the sentiment and I could make the small change to fix this, but I don't want to test against old TS-versions in future when making other changes.

I don't believe there's anyone out there using TS 1.4 and Apina. (If this really is a problem for someone, then I can certainly reconsider.)
