### ISSUE TITLE
Support ignoring fields

### ISSUE THREAD

**Issue by egaga** [EvidentSolutions/apina#22]
Remove fields with `com.fasterxml.jackson.annotation.JsonIgnore` annotation.

```
class Foo {
  public int bar = 42;

  @JsonIgnore
  public int getBar2() {
       return bar;
  }
}
```

The resulting generated object should not have `bar2: int` field.

**Comment by egaga** [comment]
Works as expected. Actually in my case there was public field foo and getFoo. Both needs to be annotated with `@JsonIgnore`

**Comment by komu** [comment]
How does Jackson behave in this case? If Jackson is OK with only one `@JsonIgnore`, we should follow suit.
