### ISSUE TITLE
Class with inherited fields are missing from generation

### ISSUE THREAD

**Issue by egaga** [EvidentSolutions/apina#23]
```
abstract class A {
   public int foo = 1;
}

class B extends A {
   public int bar = 2;
}
```

If class B is used in api response type, the generated file does not contain field foo from class A. 
Namely, inherited fields do not appear anywhere.

There should be configuration option how inheritance hierarchy is transferred to target code, e.g. by flattening the class hierarchy, or having corresponding hierarchy in target language.

**Comment by komu** [comment]
Yes, this needs to be implemented.

I'm not sure about the option though: I think it's better to do some hard thinking about which option would be best and then implement only that. If someone really needs the other option later on, it can always be added later on, but I believe at the start it's better to limit the API surface, lest we paint ourselves in a corner. If we can make it "just work" without any extra configuration and documentation, it would be best.
