### ISSUE TITLE
Support configuring context for the uriTemplate

### ISSUE THREAD

**Issue by egaga** [EvidentSolutions/apina#24]
Apina should have configuration option to set context for the uriTemplate.

Currently the Spring support module reads the type level RequestMapping in a way that having a `@RequestMapping` with a value a) `"/api/foobar"` and b) `"api/foobar"` makes a difference
for the generated uriTemplate: a) `'/api/foobar'` and b) `'api/foobar'`

The current behavior is unfortunate because now Spring controller requestmapping must be changed if requests are relative to the context path of the call-site, and arbitrary api-locations cannot be called.

So with value = "/api/foo", on the call site there should be possibility to make the call to
- `absolute-uri/${restTemplate}`, e.g. `http://example.com/bar/api/foo`
- `${call-site-context}/${restTemplate}`, e.g. `api/foo`

The uriTemplate should be the same regardless of where the context is; Apina could have a context variable that is set once for one angular application.

**Comment by komu** [comment]
Is this different from the issue #13?

**Comment by egaga** [comment]
That's exactly it. My bad, skimmed too fast the issue headlines.
