### ISSUE TITLE
Omit parameters from the method generation that are injected by the server automatically

### ISSUE THREAD

**Issue by egaga** [EvidentSolutions/apina#25]
The generated method for `void foo(int x, @CurrentUser user) {}` should be `foo(int x) {}` when arguments for @CurrentUser are defined to be resolved automatically by the server functionality, e.g. implementations of `org.springframework.web.method.support.HandlerMethodArgumentResolver`

Both annotations and types should be supported as markers that the argument is resolved automatically.
So that if class Foobar is used as automatically resolved argument, then it's always omitted from the target method generation.

**Comment by komu** [comment]
By "fields", you mean "parameters", right?

Anyway, I'm pretty sure you're describing something that has always worked. Unless a parameter is annotated by `@RequestBody`, `@RequestParam` or `@PathVariable`, it is assumed that it's something that has custom resolver. (We wouldn't know what to do with them anyway.)

We could process `@RequestHeader` -annotations similarly, but I figured that those are probably usually set by interceptors and we don't want them automatically in endpoint calls. There could be some way of forcing them as endpoint parameters if need arises, but I don't see the need right now.

See `SpringModelReader`'s [createEndpointForMethod](https://github.com/EvidentSolutions/apina/blob/master/apina-core/src/main/java/fi/evident/apina/spring/SpringModelReader.java#L67) and [parseParameter](https://github.com/EvidentSolutions/apina/blob/master/apina-core/src/main/java/fi/evident/apina/spring/SpringModelReader.java#L80) -methods for details.

**Comment by egaga** [comment]
Right, parameters, not fields.

Great to hear it works out-of-the-box.
