### ISSUE TITLE
Fail compilation if cannot resolve parameter name?

### ISSUE THREAD

**Issue by terohe** [EvidentSolutions/apina#29]
Currently Apina uses TS variable name "?" for Java arguments it cannot resolve name for.

Maybe it would be better to terminate the Apina generation in such case since "?" makes TS invalid.

https://github.com/EvidentSolutions/apina/blob/master/apina-core/src/main/java/fi/evident/apina/spring/SpringModelReader.java#L81

Invalid Typescript produced by Apina:

``` typescript
export class Foo {
    static KEY = 'fooEndpoints';

    constructor(private context: Support.EndpointContext) {
    }

    doFoo(?: Types.FooRequest): Support.IPromise<string> {
        return this.context.request({
            'uriTemplate': '/api/foo',
            'method': 'GET',
            'requestBody': this.context.serialize(?, 'FooRequest'),
            'responseType': 'string'
        });
    }

}
```

**Comment by komu** [comment]
Yes, it would be better to fail with a good error message. There's already issue #17 about this, so I'm closing this as duplicate.

I also considered about the plugin automatically adding `-parameters` to `compileJava.options.compilerArgs`, but I guess that's too much magic. Better just to give a good error message that tells the solution.

**Comment by terohe** [comment]
Ah.. missed that one. Sorry for that.

**Comment by komu** [comment]
No problem. :)
