### ISSUE TITLE
Support Spring 4.3 @GetMapping, @PostMapping etc.

### ISSUE THREAD

**Issue by ruoat** [EvidentSolutions/apina#30]
Currently Apina handles only @RequestMapping but it would be nice if @GetMapping could be used. http://www.logicbig.com/tutorials/spring-framework/spring-web-mvc/request-mapping-variants/

**Comment by komu** [comment]
Heh, just committed cba521c31c951c508641f2409b72a7383206af69 a couple of days ago with the intention of supporting this.

I won't add specific support for `@GetMapping` etc. but aim to support the Spring's meta-annotation mechanism along with `@AliasFor`, so you should be able to pluck in your own annotations as well.

Can't promise a schedule right now, but it's on my radar.

**Comment by komu** [comment]
Just released `0.6.0` with these changes.

**Comment by komu** [comment]
A word of warning, it seems that `@PostMapping(path = "/path")` works correctly, but `@PostMapping("/path")` does not. Support for implicit alias groups (multiple different aliases point to super-class aliases) seems to be lacking still.
