### ISSUE TITLE
Missing serializer for type ‘Dictionary<string>’ when translating Map<String, String>

### ISSUE THREAD

**Issue by mkel** [EvidentSolutions/apina#38]
Member  of type Map<String, String> translates to Dictionary<string>, but at runtime it raises an Error: could not find serializer for type ‘Dictionary<string>’. Should Apina automatically generate `config.registerIdentitySerializer('Dictionary<string>');` for it?

**Comment by komu** [comment]
It should certainly be automatically supported out-of-the-box, but `config.registerIdentitySerializer('Dictionary<string>')` is not the way to go. Rather Apina should register a special dictionary serializer that would use string serializer for keys and the serializer registered for type parameter for values.

So if you have `Dictionary<Foo>` and you have registered a serializer for `Foo`, it should be automatically picked up. (Unless you also override the serializer for `Dictionary<Foo>` with even more specific implementation.)

So it takes a bit more work to implement this properly for Apina. In the mean time, you can of course simply call `config.registerIdentitySerializer('Dictionary<string>');` in your own code as a workaround.

**Comment by jvmlet** [comment]
Is there release with this fix ? Thanks

**Comment by komu** [comment]
Thanks for reminding. I just published `0.15.0` which includes this.
