### ISSUE TITLE
Support polymorphism in translated classes

### ISSUE THREAD

**Issue by mohamnag** [EvidentSolutions/apina#42]
I have a REST controller which returns following resource as return value: 
```java
public class ResourceType {

    private List<SuperType> list;
    // ... setter / getters
}
```
the `SuperType` is a class as follows with two subclasses:
```java
public abstract class SuperType {

    private double sharedVar1;
    private double sharedVar2;

    // ... setter / getters
}

public class SubType1 extends SuperType {

    private final String type = "subType1";
    private double var3;

    // ... setter / getters
}

public class SubType2  extends SuperType {

    private final String type = "subType2";
    private double var4;

    // ... setter / getters
}
```
the reason that I have such structure is that, it is very important to have both types on same list on returned resource and sharing parts of structure is just a side effect.
the problem is Apina ignores the subclasses and just translates the super class:
```typescript
export class SuperType {
    sharedVar1: number;
    sharedVar2: number;
}

export class ResourceType {
    list: SuperType[];
}
```

is there a way to tell Apina considering subclasses by providing a package or similar way?

**Comment by komu** [comment]
No, there's no way to do that currently. Sounds like a good idea, though.

Between all other things, I'm afraid that I can't find time to implement this in the near future, but I'd be happy to accept a PR.

**Comment by mohamnag** [comment]
yeah fair enough, I have to see what can I do. I think that best strategy would be to support some thing like the jackson's `@JsonTypeInfo` otherwise deserialization on client side would still be impossible given only the type of superclass. There I have to see what can I do on the typescript side. Will maybe come back with some suggestions and questions.

**Comment by mohamnag** [comment]
just for reference: https://github.com/FasterXML/jackson-docs/wiki/JacksonPolymorphicDeserialization

**Comment by komu** [comment]
> I think that best strategy would be to support some thing like the jackson's @JsonTypeInfo

Yeah, sounds right.

> Will maybe come back with some suggestions and questions.

Great, I'll help as best as I can.
