### ISSUE TITLE
Use kotlin sealed class to determine subtypes

### ISSUE THREAD

**Issue by mortterna** [EvidentSolutions/apina#59]
By default jackson defines subtypes for discriminated unions using @JsonSubTypes-annotation. Jackson-module-kotlin allows lighter syntax by reading subclasses directly from sealed class using reflection. Same information could be used by apina but it needs to be read from the bytecode instead relying on kotlin-reflection.

https://github.com/FasterXML/jackson-module-kotlin/issues/239

**Comment by komu** [comment]
Now that I look at this closer, this might be quite easy to do even without access to Kotlin's own metadata. If we have `@JsonTypeInfo` without, `@JsonSubTypes`, we could just search all of the classes in the same package for subclasses. The subclasses of a sealed class need to be in the same file, which means that they will have the same package.
